version: "1"
services:
  app:
    image: saumyabhatt10642/ese-server
    ports:
      - "2000:2000"
    depends_on:
      - redis
      - prometheus
      - grafana
  redis:
    image: redis
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./src/properties/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
