version: "1"
services:
  ese-server:
    image: saumyabhatt10642/ese-server
    ports:
      - "2000:2000"
    depends_on:
      - redis-server
      - prometheus-server
      - grafana-server
  redis-server:
    image: redis
    ports:
      - "6379:6379"
  prometheus-server:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./src/properties/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana-server:
    image: grafana/grafana
    ports:
      - "3000:3000"
