{
 "title": "ESE Server Metrics",
 "description": "Internal Metrics of the ESE-Server",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Threads spawned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "changes(go_threads{job=\"ese-server\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines spawned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "changes(go_goroutines{job=\"ese-server\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap memory allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"ese-server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "changes(process_open_fds{job=\"ese-server\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Request Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "GET /",
   "type": "timeseries",
   "description": "Number of health pings made to the server",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "changes(health_ping_count{job=\"ese-server\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST /event",
   "type": "timeseries",
   "description": "No. of pings made to the `POST /event` endpoint. This will push a singular event to the server.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "changes(add_event_ping_count{job=\"ese-server\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST /events",
   "type": "timeseries",
   "description": "No. of pings made to the `POST /events` endpoint. This os called when multiple events are pushed in a single request to the server.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "changes(add_events_ping_count{job=\"ese-server\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET /events",
   "type": "timeseries",
   "description": "No. of requests handled by get events handler",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "changes(get_events_ping_count{job=\"ese-server\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}